### ISSUE TITLE
Fix compilation warnings and improve doc

### ISSUE THREAD

**Issue by ntalfer** [RumataEstor/mix_mib#1]
hi @RumataEstor thanks for your great work 

I noticed 2 warnings using Elixir 1.13 (haven't checked prior versions).

The 1st one appears when compiling mix_mib:

```
==> mix_mib
Compiling 1 file (.ex)
warning: :snmpc.compile/2 defined in application :snmp is used by the current application but the current application does not depend on :snmp. To fix this, you must do one of:

  1. If :snmp is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :snmp is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :snmp, you may optionally skip this warning by adding [xref: [exclude: [:snmpc]]] to your "def project" in mix.exs

  lib/mix_mib.ex:114: Mix.Tasks.Compile.Mibs.do_compile_mib/2
```

The 2nd appears when using this task:

```
==> my_app
warning: Mix compiler :mibs was supposed to return {:ok | :noop | :error, [diagnostic]} but it returned nil
```

Finally the compiler name that shall be indicated in the list of project compilers is `:mibs` instead of `:mix_mib`

**Comment by ntalfer** [comment]
PR: https://github.com/RumataEstor/mix_mib/pull/2

**Comment by RumataEstor** [comment]
Hi @ntalfer, I'm glad you found this library useful. And thanks for the fixes!

I haven't used this library for a while so didn't know there were some warnings produced by newer versions of Elixir.
